---
- name: ald_repo add
  template:
    src: aldpro.list.j2
    dest: /etc/apt/sources.list.d/aldpro.list

- name: aldpro client install
  ansible.builtin.apt:
    name: aldpro-client
    state: present
    update_cache: yes
  become: true
  