---
- name: aldpro dc init
  shell: |
      aldpro-server-install -d {{ domain_name | quote }} -n {{ hostname | quote }} -p {{ admin_pass | quote }} --ip {{ dc_ip | quote }} --setup_gc --setup_syncer --no-reboot
      touch /opt/rbta/aldpro/.dc_init
  args:
    creates: /opt/rbta/aldpro/.dc_init
    
  notify: reboot_server